import type { Metadata } from 'next';
import './globals.css';

import { ToastProvider } from '@/components/ui/use-toast';
import { Navigation } from '@/components/Navigation';

// Google Fonts fetchがオフライン環境で失敗するため、next/font/google は使用しない。
const inter = { variable: '' as const };

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="ja" className={inter.variable}>
      <body>
        {/* ここでグローバルにトースト機能を注入 */}
        <ToastProvider>
          <div className="flex h-screen">
            <Navigation />
            <main className="flex-1 overflow-auto">
              {children}
            </main>
          </div>
        </ToastProvider>
      </body>

    </html>
  );
}
